# Stage 1 — сборка Web-приложения
FROM node:20-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev && npm cache clean --force
COPY . .
RUN npx expo export --web --output-dir=dist

# Stage 2 — минимальный сервер (nginx)
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
