version: '3.8'

services:
  client:
    container_name: client
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - resource-server
      - auth-server
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
    networks:
      - app-network

  resource-server:
    container_name: resource-server
    build:
      context: ./transactions
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - auth-server
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
    networks:
      - app-network

  auth-server:
    container_name: auth-server
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: