domain: 127.0.0.1
resource:
  server:
    url: http://resource-server:8081
auth:
  server:
    url: http://auth-server:9000
spring:
  security:
    oauth2:
      client:
        registration:
          transactions-api:
            client-id: client-app1
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "http://${domain}:8082/login/oauth2/code/transactions-api"
            scope: read,write
            client-name: Transactions API Client
        provider:
          transactions-api:
            authorization-uri: ${auth.server.url}/oauth2/authorize
            token-uri: ${auth.server.url}/oauth2/token
server:
  port: 8082
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
        secure: true
        same-site: lax
        name: CLIENT_JSESSIONID
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG