logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.session: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web.session: TRACE

server:
  port: 8082
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
        secure: true
        same-site: lax
        name: JSESSI0NID

spring:
  security:
    oauth2:
      client:
        registration:
          transactions-api:
            client-id: client-app1
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8082/login/oauth2/code/transactions-api"
            scope: read,write
            client-name: Custom Auth Client
        provider:
          transactions-api:
            authorization-uri: http://127.0.0.1:9000/oauth2/authorize
            token-uri: http://127.0.0.1:9000/oauth2/token
