domain: 127.0.0.1
resource:
  server:
    url: http://${domain}:8082
auth:
  server:
    url: http://${domain}:8084
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: frontend-client
            client-secret: your-client-secret-here
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://${domain}:8083/login/oauth2/code/keycloak
            scope: openid,profile,email
            client-name: Keycloak Client
        provider:
          keycloak:
            authorization-uri: ${auth.server.url}/realms/what-if/protocol/openid-connect/auth
            token-uri: ${auth.server.url}/realms/what-if/protocol/openid-connect/token
            user-info-uri: ${auth.server.url}/realms/what-if/protocol/openid-connect/userinfo
            jwk-set-uri: ${auth.server.url}/realms/what-if/protocol/openid-connect/certs
            user-name-attribute: sub
            user-info-authentication-method: header
server:
  port: 8083
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
        secure: true
        same-site: lax
        name: CLIENT_JSESSIONID
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG
    com.example.config: DEBUG