spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 9000
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG

client:
  url: http://127.0.0.1:8082