spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/resourcedb
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG

auth:
  server:
    url: http://auth-server:9000