db:
  domain: postgres
spring:
  r2dbc:
    url: r2dbc:postgresql://${db.domain}:5432/resourcedb
    username: postgres
    password: postgres
server:
  port: 8081
logging:
  level:
    org.springframework.r2dbc.connection: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG
    org.springframework.context.annotation: DEBUG

auth:
  server:
    url: http://auth-server:9000