spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/resourcedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG

auth:
  server:
    url: http://auth-server:9000