CREATE TABLE account (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         user_id VARCHAR(255) NOT NULL,
                         currency VARCHAR(10) NOT NULL
);

INSERT INTO account (id, user_id, currency)
VALUES (1, 'test-user', 'USD'),
       (2, 'test-user', 'EUR');